class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'AnarRakshak',
      'appTagline': 'Your Pomegranate Farm Guard',
      'selectModelAndImage': 'Select model and pick an image',
      'modelsLoading': 'Please wait, models are loading...',
      'runningInference': 'Running inference...',
      'inferenceError': 'Inference Error',
      'modelLoadFailed': 'Model load failed: {error}',
      'inferenceFailed': 'Inference failed: {error}',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'diseaseCategory': 'Disease',
      'pestsCategory': 'Insects and Pests',
      'fruit': 'Fruit/Flower',
      'leaf': 'Leaf',
      'root': 'Root',
      'insects': 'Insects',
      'insectsDescription': 'Live/Dead insects',
      'flowers': 'Leaves/Flower/Fruit',
      'selectImageSource': 'Select Image Source',
      'featureComingSoon': 'This feature will be implemented soon.',
      // Model Labels
      'showManagementTechniques': 'Show Management\nTechniques',
      'managementTechniquesTitle': 'Management Techniques',
      'noManagementInfo': 'No management information available for this disease.',
      'ok': 'OK',
      'causalOrganismLabel': 'Causal Organism',
      'symptomsLabel': 'Symptoms',
      'predisposingFactorsLabel': 'Predisposing Factors',
      'recommendationsLabel': 'Recommendations',
      'sourceUrlLabel': 'Source',
      'confidence': 'Confidence: {score}%',
      'Bacterial Blight': 'Bacterial Blight',
      'Calyx Rot': 'Calyx Rot',
      'Fungal Cercospora': 'Fungal Cercospora',
      'Fruit Rot': 'Fruit Rot',
      'Healthy': 'Healthy',
      'Fungal Scab': 'Fungal Scab',
      'Bacterial': 'Bacterial',
      'Fungal': 'Fungal',
    },
    'hi': {
      'appTitle': 'अनाररक्षक',
      'appTagline': 'आपका अनार फार्म गार्ड',
      'selectModelAndImage': 'मॉडल चुनें और एक छवि चुनें',
      'modelsLoading': 'कृपया प्रतीक्षा करें, मॉडल लोड हो रहे हैं...',
      'runningInference': 'अनुमान चल रहा है...',
      'inferenceError': 'अनुमान में त्रुटि',
      'modelLoadFailed': 'मॉडल लोड विफल: {error}',
      'inferenceFailed': 'अनुमान विफल: {error}',
      'gallery': 'गैलरी',
      'camera': 'कैमरा',
      'diseaseCategory': 'रोग',
      'pestsCategory': 'कीड़े और कीट',
      'fruit': 'फल और फूल',
      'leaf': 'पत्ती',
      'root': 'जड़',
      'insects': 'कीड़े',
      'insectsDescription': 'जीवित/मृत कीड़े',
      'flowers': 'पत्तियां/फूल/फल',
      'selectImageSource': 'छवि स्रोत चुनें',
      'featureComingSoon': 'यह सुविधा जल्द ही लागू की जाएगी।',
      // Model Labels
      'showManagementTechniques': 'प्रबंधन तकनीकें\nदिखाएं',
      'managementTechniquesTitle': 'प्रबंधन तकनीकें',
      'noManagementInfo': 'इस रोग के लिए कोई प्रबंधन जानकारी उपलब्ध नहीं है।',
      'ok': 'ठीक है',
      'causalOrganismLabel': 'कारण जीव',
      'symptomsLabel': 'लक्षण',
      'predisposingFactorsLabel': 'अनुकूल कारक',
      'recommendationsLabel': 'सिफारिशें',
      'sourceUrlLabel': 'स्रोत',
      'confidence': 'सटीकता: {score}%',
      'Bacterial Blight': 'जीवाणु झुलसा',
      'Calyx Rot': 'कैलिक्स रॉट',
      'Fungal Cercospora': 'फंगल सर्कोस्पोरा',
      'Fruit Rot': 'फल सड़न',
      'Healthy': 'स्वस्थ',
      'Fungal Scab': 'फंगल स्कैब',
      'Bacterial': 'जीवाणु',
      'Fungal': 'कवक',
    },
    'gu': {
      'appTitle': 'અનારરક્ષક',
      'appTagline': 'તમારા દાડમના ફાર્મનો રક્ષક',
      'selectModelAndImage': 'મોડેલ પસંદ કરો અને છબી પસંદ કરો',
      'modelsLoading': 'કૃપા કરીને રાહ જુઓ, મોડેલ લોડ થઈ રહ્યા છે...',
      'runningInference': 'અનુમાન ચાલી રહ્યું છે...',
      'inferenceError': 'અનુમાનમાં ભૂલ',
      'modelLoadFailed': 'મોડેલ લોડ નિષ્ફળ: {error}',
      'inferenceFailed': 'અનુમાન નિષ્ફળ: {error}',
      'gallery': 'ગેલેરી',
      'camera': 'કેમેરા',
      'diseaseCategory': 'રોગ',
      'pestsCategory': 'જંતુઓ અને જીવાતો',
      'fruit': 'ફળ/ફૂલ',
      'leaf': 'પાન',
      'root': 'મૂળ',
      'insects': 'જંતુઓ',
      'insectsDescription': 'જીવંત/મૃત જંતુઓ',
      'flowers': 'પાંદડા/ફૂલ/ફળ',
      'selectImageSource': 'છબીનો સ્ત્રોત પસંદ કરો',
      'featureComingSoon': 'આ સુવિધા ટૂંક સમયમાં લાગુ કરવામાં આવશે.',
      'showManagementTechniques': 'વ્યવસ્થાપન તકનીકો\nબતાવો',
      'managementTechniquesTitle': 'વ્યવસ્થાપન તકનીકો',
      'noManagementInfo': 'આ રોગ માટે કોઈ વ્યવસ્થાપન માહિતી ઉપલબ્ધ નથી.',
      'ok': 'ઠીક છે',
      'causalOrganismLabel': 'કારક જીવ',
      'symptomsLabel': 'લક્ષણો',
      'predisposingFactorsLabel': 'પૂર્વગ્રહયુક્ત પરિબળો',
      'recommendationsLabel': 'ભલામણો',
      'sourceUrlLabel': 'સ્ત્રોત',
      'confidence': 'ચોકસાઈ: {score}%',
      'Bacterial Blight': 'બેક્ટેરિયલ બ્લાઇટ',
      'Calyx Rot': 'કેલિક્સ રોટ',
      'Fungal Cercospora': 'ફંગલ સર્કોસ્પોરા',
      'Fruit Rot': 'ફળનો સડો',
      'Healthy': 'સ્વસ્થ',
      'Fungal Scab': 'ફંગલ સ્કેબ',
      'Bacterial': 'બેક્ટેરિયલ',
      'Fungal': 'ફંગલ',
    },
    'mr': {
      'appTitle': 'अनाररक्षक',
      'appTagline': 'तुमचा डाळिंब फार्म गार्ड',
      'selectModelAndImage': 'मॉडेल निवडा आणि एक प्रतिमा निवडा',
      'modelsLoading': 'कृपया थांबा, मॉडेल्स लोड होत आहेत...',
      'runningInference': 'अनुमान चालू आहे...',
      'inferenceError': 'अनुमानात त्रुटी',
      'modelLoadFailed': 'मॉडेल लोड अयशस्वी: {error}',
      'inferenceFailed': 'अनुमान अयशस्वी: {error}',
      'gallery': 'गॅलरी',
      'camera': 'कॅमेरा',
      'diseaseCategory': 'रोग',
      'pestsCategory': 'कीटक आणि कीड',
      'fruit': 'फळ/फूल',
      'leaf': 'पान',
      'root': 'मूळ',
      'insects': 'कीटक',
      'insectsDescription': 'जिवंत/मृत कीटक',
      'flowers': 'पाने/फुले/फळे',
      'selectImageSource': 'प्रतिमा स्रोत निवडा',
      'featureComingSoon': 'हे वैशिष्ट्य लवकरच लागू केले जाईल.',
      'showManagementTechniques': 'व्यवस्थापन तंत्र\nदाखवा',
      'managementTechniquesTitle': 'व्यवस्थापन तंत्र',
      'noManagementInfo': 'या रोगासाठी कोणतीही व्यवस्थापन माहिती उपलब्ध नाही.',
      'ok': 'ठीक आहे',
      'causalOrganismLabel': 'कारक जीव',
      'symptomsLabel': 'लक्षणे',
      'predisposingFactorsLabel': 'अनुकूल घटक',
      'recommendationsLabel': 'शिफारसी',
      'sourceUrlLabel': 'स्रोत',
      'confidence': 'अचूकता: {score}%',
      'Bacterial Blight': 'बॅक्टेरियल ब्लाइट',
      'Calyx Rot': 'कॅलिक्स रॉट',
      'Fungal Cercospora': 'फंगल सर्कोस्पोरा',
      'Fruit Rot': 'फळांची सड',
      'Healthy': 'निरोगी',
      'Fungal Scab': 'फंगल स्कॅब',
      'Bacterial': 'बॅक्टेरियल',
      'Fungal': 'बुरशीजन्य',
    },
    'kn': {
      'appTitle': 'ಅನಾರರಕ್ಷಕ',
      'appTagline': 'ನಿಮ್ಮ ದಾಳಿಂಬೆ ಫಾರ್ಮ್ ಗಾರ್ಡ್',
      'selectModelAndImage': 'ಮಾದರಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಚಿತ್ರವನ್ನು ಆರಿಸಿ',
      'modelsLoading': 'ದಯವಿಟ್ಟು ನಿರೀಕ್ಷಿಸಿ, ಮಾದರಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...',
      'runningInference': 'ಊಹೆ ನಡೆಯುತ್ತಿದೆ...',
      'inferenceError': 'ಊಹೆಯಲ್ಲಿ ದೋಷ',
      'modelLoadFailed': 'ಮಾದರಿ ಲೋಡ್ ವಿಫಲವಾಗಿದೆ: {error}',
      'inferenceFailed': 'ಊಹೆ ವಿಫಲವಾಗಿದೆ: {error}',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'camera': 'ಕ್ಯಾಮೆರಾ',
      'diseaseCategory': 'ರೋಗ',
      'pestsCategory': 'ಕೀಟಗಳು ಮತ್ತು ಕ್ರಿಮಿಗಳು',
      'fruit': 'ಹಣ್ಣು/ಹೂವು',
      'leaf': 'ಎಲೆ',
      'root': 'ಬೇರು',
      'insects': 'ಕೀಟಗಳು',
      'insectsDescription': 'ಜೀವಂತ/ಸತ್ತ ಕೀಟಗಳು',
      'flowers': 'ಎಲೆಗಳು/ಹೂವು/ಹಣ್ಣು',
      'selectImageSource': 'ಚಿತ್ರದ ಮೂಲವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'featureComingSoon': 'ಈ ವೈಶಿಷ್ಟ್ಯವನ್ನು ಶೀಘ್ರದಲ್ಲೇ ಜಾರಿಗೆ ತರಲಾಗುವುದು.',
      'showManagementTechniques': 'ನಿರ್ವಹಣಾ ತಂತ್ರಗಳನ್ನು\nತೋರಿಸಿ',
      'managementTechniquesTitle': 'ನಿರ್ವಹಣಾ ತಂತ್ರಗಳು',
      'noManagementInfo': 'ಈ ರೋಗಕ್ಕೆ ಯಾವುದೇ ನಿರ್ವಹಣಾ ಮಾಹಿತಿ ಲಭ್ಯವಿಲ್ಲ.',
      'ok': 'ಸರಿ',
      'causalOrganismLabel': 'ಕಾರಕ ಜೀವಿ',
      'symptomsLabel': 'ಲಕ್ಷಣಗಳು',
      'predisposingFactorsLabel': 'ಪೂರಕ ಅಂಶಗಳು',
      'recommendationsLabel': 'ಶಿಫಾರಸುಗಳು',
      'sourceUrlLabel': 'ಮೂಲ',
      'confidence': 'ನಿಖರತೆ: {score}%',
      'Bacterial Blight': 'ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಬ್ಲೈಟ್',
      'Calyx Rot': 'ಕ್ಯಾಲಿಕ್ಸ್ ರಾಟ್',
      'Fungal Cercospora': 'ಫಂಗಲ್ ಸರ್ಕೋಸ್ಪೊರಾ',
      'Fruit Rot': 'ಹಣ್ಣಿನ ಕೊಳೆತ',
      'Healthy': 'ಆರೋಗ್ಯಕರ',
      'Fungal Scab': 'ಫಂಗಲ್ ಸ್ಕ್ಯಾಬ್',
      'Bacterial': 'ಬ್ಯಾಕ್ಟೀರಿಯಲ್',
      'Fungal': 'ಫಂಗಲ್',
    },
    'te': {
      'appTitle': 'అనారరక్షక్',
      'appTagline': 'మీ దానిమ్మ ఫార్మ్ గార్డ్',
      'selectModelAndImage': 'మోడల్‌ని ఎంచుకుని, చిత్రాన్ని ఎంచుకోండి',
      'modelsLoading': 'దయచేసి వేచి ఉండండి, మోడల్‌లు లోడ్ అవుతున్నాయి...',
      'runningInference': 'అంచనా నడుస్తోంది...',
      'inferenceError': 'అంచనాలో లోపం',
      'modelLoadFailed': 'మోడల్ లోడ్ విఫలమైంది: {error}',
      'inferenceFailed': 'అంచనా విఫలమైంది: {error}',
      'gallery': 'గ్యాలరీ',
      'camera': 'కెమెరా',
      'diseaseCategory': 'వ్యాధి',
      'pestsCategory': 'కీటకాలు మరియు తెగుళ్లు',
      'fruit': 'పండు/పువ్వు',
      'leaf': 'ఆకు',
      'root': 'వేరు',
      'insects': 'కీటకాలు',
      'insectsDescription': 'సజీవ/చనిపోయిన కీటకాలు',
      'flowers': 'ఆకులు/పువ్వు/పండు',
      'selectImageSource': 'చిత్ర మూలాన్ని ఎంచుకోండి',
      'featureComingSoon': 'ఈ ఫీచర్ త్వరలో అమలు చేయబడుతుంది.',
      'showManagementTechniques': 'నిర్వహణ పద్ధతులను\nచూపించు',
      'managementTechniquesTitle': 'నిర్వహణ పద్ధతులు',
      'noManagementInfo': 'ఈ వ్యాధికి నిర్వహణ సమాచారం అందుబాటులో లేదు.',
      'ok': 'సరే',
      'causalOrganismLabel': 'కారక జీవి',
      'symptomsLabel': 'లక్షణాలు',
      'predisposingFactorsLabel': 'అనుకూల కారకాలు',
      'recommendationsLabel': 'సిఫార్సులు',
      'sourceUrlLabel': 'మూలం',
      'confidence': 'ఖచ్చితత్వం: {score}%',
      'Bacterial Blight': 'బాక్టీరియల్ బ్లైట్',
      'Calyx Rot': 'కాలిక్స్ రాట్',
      'Fungal Cercospora': 'ఫంగల్ సెర్కోస్పోరా',
      'Fruit Rot': 'పండు కుళ్ళు',
      'Healthy': 'ఆరోగ్యకరమైన',
      'Fungal Scab': 'ఫంగల్ స్కాబ్',
      'Bacterial': 'బాక్టీరియల్',
      'Fungal': 'ఫంగల్',
    },
  };

  String get(String key) {
    return _localizedValues[languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  String getWithParam(String key, Map<String, String> params) {
    String value = get(key);
    params.forEach((paramKey, paramValue) {
      value = value.replaceAll('{$paramKey}', paramValue);
    });
    return value;
  }
}